package java;

public class EvenFibonacci {
    /**
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
     * By starting with 1 and 2, the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
     * find the sum of the even-valued terms.
     * @param args
     */

    public static void main(String[] args) {
        EvenFibonacci.sum();
    }

    public static void sum(){
        int limit = 4_000_000;
        int previous=1, last=2, next =0, sum = last;

        while(true){
            next = previous + last;
            System.out.println(next);
            if(next>limit){
                break;
            }
            if(next % 2 == 0){
                sum += next;
            }
            previous = last;
            last = next;
        }
        System.out.println("sum "+sum);
    }
}
